default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  adapter: postgresql
  password: 12345678
  username: postgres
  host: localhost
  min_messages: warning

development:
  <<: *default
  database: temple-management-system-development
  
test:
  <<: *default
  database: temple-management-system-test

production:
  <<: *default
  database: temple-management-system-production
