default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  # adapter: postgresql
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASS') %>
  host: localhost
  min_messages: warning

development:
  <<: *default
  database: temple-management-system-development
  
test:
  <<: *default
  database: temple-management-system-test

production:
  <<: *default
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: temple-management-system-production
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASS') %>
  